### ISSUE TITLE
extra stages run when specific stage invoked

### ISSUE THREAD

**Issue by jgangemi** [srevinsaju/togomak#26]
there are times a `togmak run <stage>` will invoke other stages in the file when it should not.

**Comment by srevinsaju** [comment]
I will need a way to reproduce that, I think I forgot the scenario where this happens

**Comment by jgangemi** [comment]
if memory serves, this happens when using `togomak run <stage>`. 

i have been working around this using `togomak root +<stage>`

**Comment by srevinsaju** [comment]
Using the `togomak.hcl` at the root of the directory, it seems to be working...

![image](https://github.com/srevinsaju/togomak/assets/48695438/85f08184-26ea-402d-94b9-7f92fc63e849)

**Comment by jgangemi** [comment]
try running one of the stages that would run in the middle if the entire file was executed.

**Comment by srevinsaju** [comment]
With togomak v2, this behavior has changed to a desirable set up - see https://togomak.srev.in/docs/cli/usage for a details list of examples
